INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (1,'NORMAL','David','123456');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (2,'NORMAL','david','123456');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (3,'NORMAL','David','1234567');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (4,'NORMAL','John','987654');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (5,'BUSINESS','David','123456');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (6,'BUSINESS','david','123456');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (7,'BUSINESS','David','1234567');
INSERT INTO ADDRESS_BOOK(ID,BOOK,"NAME",PHONE_NUMBER) VALUES (8,'BUSINESS','John','987654');