CREATE TABLE ADDRESS_BOOK(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BOOK VARCHAR(10) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX INDEX_ADD_BOOK on ADDRESS_BOOK(BOOK);